config/routes.rb
Rails.application.routes.draw do
  get 'items/show'

  get 'home/index'

   root 'home#index'

  resources :items

end

app/models/auction.rb
class Auction < ActiveRecord::Base
  validates :auc_id, presence: true
  validates :item, presence: true
  validates :owner, presence: true
  validates :owner_realm, presence: true
  validates :bid, presence: true
  validates :buyout, presence: true
  validates :quantity, presence: true
  validates :time_left, presence: true

end

app/models/item.rb
class Item < ActiveRecord::Base
  validates :item_id, presence: true
  validates :name, presence: true
  validates :stackable, presence: true
  validates :icon, presence: true
  validates :buy_price, presence: true
  validates :sell_price, presence: true
  validates :is_auctionable, presence: true
  validates :item_level, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def show
    @item = Item.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/home/index.html.erb
<h1>Auction House Data</h1>
<%= form_tag do %>
<input/><button>Search</button>
<% end %>

app/views/items/show.html.erb
<h1>Items#show</h1>
<p>Find me in app/views/items/show.html.erb</p>
<h2><%= @item.name %></h2>
<img src="http://us.media.blizzard.com/wow/icons/56/<%= @item.icon %>.jpg"></img>
<ul>
  <li>Buy Price: <%= @item.buy_price %></li>
  <li>Sell Price: <%= @item.sell_price %></li>
  <li>Item Level: <%= @item.item_level %></li>
</ul>
<%= link_to "Back to search", home_index_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AuctionHouse</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>